### ISSUE TITLE
Complete Monorepo Integration 

### ISSUE THREAD

**Issue by FermiDirak** [flexport/latitude#36]
Overaching project: https://github.com/flexport/latitude/projects/1
Open sourcing Latitude PR https://github.flexport.io/flexport/flexport/pull/53510

Work to be complete before OS Latitude can be integrated with the monorepo:

- [ ] Documentation
  - [x] Writing a README.md https://github.com/flexport/latitude/issues/9
  - [ ] Writing contribution docs https://github.com/flexport/latitude/issues/26
- [ ] Integration with the monorepo https://github.com/flexport/latitude/issues/24
- [ ] create a sample internal contribution

**Comment by ddzoan** [comment]
Separate i18n specific to latitude
